package tp.caperucita.search.auxiliar;

public class ConfiguracionInicial {
	
	public static Integer cantidadDeVidas = 3, cantidadDulces = 0 ;
		
	//Escenario 1
	public static PosicionCelda posicionInicialCaperucita = new PosicionCelda(5,11);
	public static ContenidoCelda[][] mapaAmbiente = {
			{ContenidoCelda.OBSTACULO, ContenidoCelda.OBSTACULO, ContenidoCelda.OBSTACULO, ContenidoCelda.OBSTACULO, ContenidoCelda.OBSTACULO,ContenidoCelda.OBSTACULO, ContenidoCelda.OBSTACULO, ContenidoCelda.OBSTACULO,ContenidoCelda.OBSTACULO, ContenidoCelda.OBSTACULO, ContenidoCelda.OBSTACULO,ContenidoCelda.OBSTACULO,ContenidoCelda.OBSTACULO, ContenidoCelda.OBSTACULO},
			{ContenidoCelda.OBSTACULO, ContenidoCelda.OBSTACULO, ContenidoCelda.OBSTACULO, ContenidoCelda.DULCE,     ContenidoCelda.LIBRE,    ContenidoCelda.LIBRE,     ContenidoCelda.LIBRE,     ContenidoCelda.OBSTACULO,ContenidoCelda.LIBRE,     ContenidoCelda.LIBRE,     ContenidoCelda.DULCE,    ContenidoCelda.OBSTACULO,ContenidoCelda.OBSTACULO, ContenidoCelda.OBSTACULO},
			{ContenidoCelda.OBSTACULO, ContenidoCelda.OBSTACULO, ContenidoCelda.OBSTACULO, ContenidoCelda.LIBRE,     ContenidoCelda.OBSTACULO,ContenidoCelda.LIBRE,     ContenidoCelda.LIBRE,     ContenidoCelda.LIBRE,    ContenidoCelda.LIBRE,     ContenidoCelda.LIBRE,     ContenidoCelda.LIBRE,    ContenidoCelda.LIBRE,    ContenidoCelda.OBSTACULO, ContenidoCelda.OBSTACULO},
			{ContenidoCelda.OBSTACULO, ContenidoCelda.OBSTACULO, ContenidoCelda.OBSTACULO, ContenidoCelda.LIBRE,     ContenidoCelda.LIBRE,    ContenidoCelda.LIBRE,     ContenidoCelda.LIBRE,     ContenidoCelda.LIBRE,    ContenidoCelda.DULCE,     ContenidoCelda.OBSTACULO, ContenidoCelda.LIBRE,    ContenidoCelda.LIBRE,    ContenidoCelda.OBSTACULO, ContenidoCelda.OBSTACULO},
			{ContenidoCelda.OBSTACULO, ContenidoCelda.OBSTACULO, ContenidoCelda.OBSTACULO, ContenidoCelda.OBSTACULO, ContenidoCelda.OBSTACULO,ContenidoCelda.LIBRE,     ContenidoCelda.LIBRE,     ContenidoCelda.LIBRE,    ContenidoCelda.OBSTACULO, ContenidoCelda.LIBRE,     ContenidoCelda.LIBRE,    ContenidoCelda.LIBRE,    ContenidoCelda.OBSTACULO, ContenidoCelda.OBSTACULO},
			{ContenidoCelda.OBSTACULO, ContenidoCelda.OBSTACULO, ContenidoCelda.OBSTACULO, ContenidoCelda.LIBRE,     ContenidoCelda.OBSTACULO,ContenidoCelda.OBSTACULO, ContenidoCelda.LIBRE,     ContenidoCelda.LIBRE,    ContenidoCelda.LIBRE,     ContenidoCelda.LIBRE,     ContenidoCelda.LIBRE,    ContenidoCelda.LIBRE,    ContenidoCelda.OBSTACULO, ContenidoCelda.OBSTACULO},
			{ContenidoCelda.OBSTACULO, ContenidoCelda.OBSTACULO, ContenidoCelda.OBSTACULO, ContenidoCelda.LIBRE,     ContenidoCelda.LIBRE,    ContenidoCelda.OBSTACULO, ContenidoCelda.OBSTACULO, ContenidoCelda.OBSTACULO,ContenidoCelda.LIBRE,     ContenidoCelda.OBSTACULO, ContenidoCelda.LIBRE,    ContenidoCelda.OBSTACULO,ContenidoCelda.OBSTACULO, ContenidoCelda.OBSTACULO},
			{ContenidoCelda.OBSTACULO, ContenidoCelda.OBSTACULO, ContenidoCelda.OBSTACULO, ContenidoCelda.LIBRE,     ContenidoCelda.LIBRE,    ContenidoCelda.LIBRE,     ContenidoCelda.OBSTACULO, ContenidoCelda.FLORES,   ContenidoCelda.LIBRE,     ContenidoCelda.LIBRE,     ContenidoCelda.LIBRE,    ContenidoCelda.OBSTACULO,ContenidoCelda.OBSTACULO, ContenidoCelda.OBSTACULO},
			{ContenidoCelda.OBSTACULO, ContenidoCelda.OBSTACULO, ContenidoCelda.OBSTACULO, ContenidoCelda.OBSTACULO, ContenidoCelda.OBSTACULO,ContenidoCelda.OBSTACULO, ContenidoCelda.OBSTACULO, ContenidoCelda.FLORES,   ContenidoCelda.OBSTACULO, ContenidoCelda.OBSTACULO, ContenidoCelda.OBSTACULO,ContenidoCelda.OBSTACULO,ContenidoCelda.OBSTACULO, ContenidoCelda.OBSTACULO}
	};
	
	//Escenario 2
//	public static PosicionCelda posicionInicialCaperucita = new PosicionCelda(6,3);
//	public static ContenidoCelda[][] mapaAmbiente =  {
//			{ContenidoCelda.OBSTACULO, ContenidoCelda.OBSTACULO, ContenidoCelda.OBSTACULO, ContenidoCelda.OBSTACULO, ContenidoCelda.OBSTACULO, ContenidoCelda.OBSTACULO, ContenidoCelda.OBSTACULO, ContenidoCelda.OBSTACULO, ContenidoCelda.OBSTACULO, ContenidoCelda.OBSTACULO, ContenidoCelda.OBSTACULO, ContenidoCelda.OBSTACULO,ContenidoCelda.OBSTACULO,ContenidoCelda.OBSTACULO},
//			{ContenidoCelda.OBSTACULO, ContenidoCelda.OBSTACULO, ContenidoCelda.OBSTACULO, ContenidoCelda.OBSTACULO, ContenidoCelda.OBSTACULO, ContenidoCelda.DULCE,     ContenidoCelda.LIBRE,     ContenidoCelda.OBSTACULO, ContenidoCelda.OBSTACULO, ContenidoCelda.OBSTACULO, ContenidoCelda.OBSTACULO, ContenidoCelda.OBSTACULO,    ContenidoCelda.OBSTACULO,ContenidoCelda.OBSTACULO},
//			{ContenidoCelda.OBSTACULO, ContenidoCelda.OBSTACULO, ContenidoCelda.OBSTACULO, ContenidoCelda.OBSTACULO, ContenidoCelda.LIBRE,     ContenidoCelda.LIBRE,     ContenidoCelda.LIBRE,     ContenidoCelda.OBSTACULO, ContenidoCelda.OBSTACULO, ContenidoCelda.LIBRE,     ContenidoCelda.OBSTACULO, ContenidoCelda.OBSTACULO,    ContenidoCelda.OBSTACULO,    ContenidoCelda.OBSTACULO},
//			{ContenidoCelda.OBSTACULO, ContenidoCelda.OBSTACULO, ContenidoCelda.OBSTACULO, ContenidoCelda.OBSTACULO, ContenidoCelda.OBSTACULO, ContenidoCelda.LIBRE,     ContenidoCelda.LIBRE,     ContenidoCelda.LIBRE,     ContenidoCelda.DULCE,     ContenidoCelda.LIBRE,     ContenidoCelda.LIBRE,     ContenidoCelda.OBSTACULO,    ContenidoCelda.OBSTACULO,    ContenidoCelda.OBSTACULO},
//			{ContenidoCelda.OBSTACULO, ContenidoCelda.OBSTACULO, ContenidoCelda.OBSTACULO, ContenidoCelda.LIBRE,     ContenidoCelda.OBSTACULO, ContenidoCelda.OBSTACULO, ContenidoCelda.LIBRE,     ContenidoCelda.OBSTACULO, ContenidoCelda.LIBRE,     ContenidoCelda.OBSTACULO, ContenidoCelda.DULCE,     ContenidoCelda.OBSTACULO,    ContenidoCelda.OBSTACULO,    ContenidoCelda.OBSTACULO},
//			{ContenidoCelda.OBSTACULO, ContenidoCelda.OBSTACULO, ContenidoCelda.OBSTACULO, ContenidoCelda.LIBRE,     ContenidoCelda.LIBRE,     ContenidoCelda.OBSTACULO, ContenidoCelda.LIBRE,     ContenidoCelda.OBSTACULO, ContenidoCelda.LIBRE,     ContenidoCelda.OBSTACULO, ContenidoCelda.LIBRE,     ContenidoCelda.OBSTACULO,    ContenidoCelda.OBSTACULO,    ContenidoCelda.OBSTACULO},
//			{ContenidoCelda.OBSTACULO, ContenidoCelda.OBSTACULO, ContenidoCelda.OBSTACULO, ContenidoCelda.LIBRE,     ContenidoCelda.LIBRE,     ContenidoCelda.LIBRE,     ContenidoCelda.LIBRE,     ContenidoCelda.LIBRE,     ContenidoCelda.LIBRE,     ContenidoCelda.OBSTACULO, ContenidoCelda.LIBRE,     ContenidoCelda.OBSTACULO,    ContenidoCelda.OBSTACULO,ContenidoCelda.OBSTACULO},
//			{ContenidoCelda.OBSTACULO, ContenidoCelda.OBSTACULO, ContenidoCelda.OBSTACULO, ContenidoCelda.OBSTACULO, ContenidoCelda.OBSTACULO, ContenidoCelda.OBSTACULO, ContenidoCelda.FLORES,    ContenidoCelda.OBSTACULO, ContenidoCelda.LIBRE,     ContenidoCelda.LIBRE,     ContenidoCelda.LIBRE,     ContenidoCelda.OBSTACULO,    ContenidoCelda.OBSTACULO,ContenidoCelda.OBSTACULO},
//			{ContenidoCelda.OBSTACULO, ContenidoCelda.OBSTACULO, ContenidoCelda.OBSTACULO, ContenidoCelda.OBSTACULO, ContenidoCelda.OBSTACULO, ContenidoCelda.OBSTACULO, ContenidoCelda.FLORES,    ContenidoCelda.OBSTACULO, ContenidoCelda.OBSTACULO, ContenidoCelda.OBSTACULO, ContenidoCelda.OBSTACULO, ContenidoCelda.OBSTACULO,ContenidoCelda.OBSTACULO,ContenidoCelda.OBSTACULO}
//	};

	//Escenario 3
//		public static PosicionCelda posicionInicialCaperucita = new PosicionCelda(4,11);
//		public static ContenidoCelda[][] mapaAmbiente = {
//				{ContenidoCelda.OBSTACULO, ContenidoCelda.OBSTACULO, ContenidoCelda.OBSTACULO, ContenidoCelda.FLORES,    ContenidoCelda.OBSTACULO, ContenidoCelda.OBSTACULO, ContenidoCelda.OBSTACULO, ContenidoCelda.OBSTACULO, ContenidoCelda.OBSTACULO, ContenidoCelda.OBSTACULO, ContenidoCelda.OBSTACULO, ContenidoCelda.OBSTACULO, ContenidoCelda.OBSTACULO, ContenidoCelda.OBSTACULO},
//				{ContenidoCelda.OBSTACULO, ContenidoCelda.OBSTACULO, ContenidoCelda.OBSTACULO, ContenidoCelda.FLORES,    ContenidoCelda.OBSTACULO, ContenidoCelda.LIBRE,     ContenidoCelda.LIBRE,     ContenidoCelda.LIBRE,     ContenidoCelda.OBSTACULO, ContenidoCelda.OBSTACULO, ContenidoCelda.OBSTACULO, ContenidoCelda.LIBRE,     ContenidoCelda.OBSTACULO, ContenidoCelda.OBSTACULO},
//				{ContenidoCelda.OBSTACULO, ContenidoCelda.OBSTACULO, ContenidoCelda.OBSTACULO, ContenidoCelda.LIBRE,     ContenidoCelda.OBSTACULO, ContenidoCelda.LIBRE,     ContenidoCelda.OBSTACULO, ContenidoCelda.DULCE,     ContenidoCelda.OBSTACULO, ContenidoCelda.LIBRE,     ContenidoCelda.OBSTACULO, ContenidoCelda.OBSTACULO, ContenidoCelda.OBSTACULO, ContenidoCelda.OBSTACULO},
//				{ContenidoCelda.OBSTACULO, ContenidoCelda.OBSTACULO, ContenidoCelda.OBSTACULO, ContenidoCelda.LIBRE,     ContenidoCelda.LIBRE,     ContenidoCelda.LIBRE,     ContenidoCelda.LIBRE,     ContenidoCelda.LIBRE,     ContenidoCelda.LIBRE,     ContenidoCelda.OBSTACULO, ContenidoCelda.LIBRE,     ContenidoCelda.OBSTACULO, ContenidoCelda.OBSTACULO, ContenidoCelda.OBSTACULO},
//				{ContenidoCelda.OBSTACULO, ContenidoCelda.OBSTACULO, ContenidoCelda.OBSTACULO, ContenidoCelda.OBSTACULO, ContenidoCelda.OBSTACULO, ContenidoCelda.LIBRE,     ContenidoCelda.LIBRE,     ContenidoCelda.LIBRE,     ContenidoCelda.LIBRE,     ContenidoCelda.LIBRE,     ContenidoCelda.LIBRE,     ContenidoCelda.LIBRE,     ContenidoCelda.OBSTACULO, ContenidoCelda.OBSTACULO},
//				{ContenidoCelda.OBSTACULO, ContenidoCelda.OBSTACULO, ContenidoCelda.OBSTACULO, ContenidoCelda.LIBRE,     ContenidoCelda.LIBRE,     ContenidoCelda.LIBRE,     ContenidoCelda.LIBRE,     ContenidoCelda.OBSTACULO, ContenidoCelda.LIBRE,     ContenidoCelda.OBSTACULO, ContenidoCelda.LIBRE,     ContenidoCelda.LIBRE,     ContenidoCelda.OBSTACULO, ContenidoCelda.OBSTACULO},
//				{ContenidoCelda.OBSTACULO, ContenidoCelda.OBSTACULO, ContenidoCelda.OBSTACULO, ContenidoCelda.LIBRE,     ContenidoCelda.DULCE,     ContenidoCelda.LIBRE,     ContenidoCelda.LIBRE,     ContenidoCelda.OBSTACULO, ContenidoCelda.DULCE,     ContenidoCelda.LIBRE,     ContenidoCelda.OBSTACULO, ContenidoCelda.LIBRE,     ContenidoCelda.OBSTACULO, ContenidoCelda.OBSTACULO},
//				{ContenidoCelda.OBSTACULO, ContenidoCelda.OBSTACULO, ContenidoCelda.OBSTACULO, ContenidoCelda.OBSTACULO, ContenidoCelda.OBSTACULO, ContenidoCelda.OBSTACULO, ContenidoCelda.LIBRE,     ContenidoCelda.LIBRE,     ContenidoCelda.LIBRE,     ContenidoCelda.OBSTACULO, ContenidoCelda.OBSTACULO, ContenidoCelda.OBSTACULO, ContenidoCelda.OBSTACULO, ContenidoCelda.OBSTACULO},
//				{ContenidoCelda.OBSTACULO, ContenidoCelda.OBSTACULO, ContenidoCelda.OBSTACULO, ContenidoCelda.OBSTACULO, ContenidoCelda.OBSTACULO, ContenidoCelda.OBSTACULO, ContenidoCelda.OBSTACULO, ContenidoCelda.OBSTACULO, ContenidoCelda.OBSTACULO, ContenidoCelda.OBSTACULO, ContenidoCelda.OBSTACULO, ContenidoCelda.OBSTACULO, ContenidoCelda.OBSTACULO, ContenidoCelda.OBSTACULO}
//		};

	public ConfiguracionInicial() {
		
	}
}
